### ISSUE TITLE
Upgrade to {N} 3.4.3 from 3.3.1 build failed with an exception

### ISSUE THREAD

**Issue by stevegardnersa** [hypery2k/nativescript-fabric#123]
I've looked at the other issues and this seems like it could be related to #114 but not the same error. I 
tried using nativescript-fabric@1.0.6-ci-build-19 but no luck.

After updating {N} to 3.4.3 from 3.3.1 when building I get the following error...

> + adding aar plugin dependency: /Users/stevegardner/Projects/Nativescript/GFConnectNS/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
> false
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/stevegardner/Projects/Nativescript/GFConnectNS/platforms/android/build-tools/fabric-devtools/build.gradle' line: 12
> 
> * What went wrong:
> A problem occurred evaluating project ':fabric'.
>  Failed to apply plugin [id 'io.fabric']
>     Crashlytics was applied to a project without an Android plugin. Please make sure the Crashlytics plugin is applied after the appropriate Android plugin for your project.
> 

I removed hooks, node_modules and platforms folders and rebuilt but same issue occurs. 

**NativeScript version:** 3.4.3
**tns-core-modules:** 3.4.1
**tns-android:** 3.4.2
**Java version:** "1.8.0_162"
**NPM:** 5.6.0
**Node:** 9.8.0
**Platform(s) running:** Android

**Comment by stevegardnersa** [comment]
I did some further digging and made the following change to _node_modules/nativescript-fabric/lib/after-prepare.js_ by adding `apply plugin: 'com.android.application'` before `apply plugin: 'io.fabric'`

This change fixed the build issue but now when livesync is triggered after a file change I get the following error...

`TypeError: fs.pathExistsSync is not a function
    at /Users/stevegardner/Projects/Nativescript/GFConnectNS/hooks/after-prepare/nativescript-fabric-gradle.js:87:18
    at xfs.stat (/Users/stevegardner/Projects/Nativescript/GFConnectNS/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/stevegardner/Projects/Nativescript/GFConnectNS/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:171:5)
`

Has anyone had this same issue. Any idea what to try next?

**Comment by stevegardnersa** [comment]
I continued my digging and got past this issue by doing the following. This seems to have resolved all my issues.

In `hooks/after-prepare/nativescript-fabric-gradle.js` I commented out a few lines to leave the code as below.

```javascript
      // hack for node resolution not working in some cases
      //try {        
        //fs = require("fs-extra");
      //} catch (ignored) {
        fs = require("../../node_modules/nativescript-fabric/node_modules/fs-extra/lib/index.js");
      //}
```

**Comment by frapaa** [comment]
Awesome findings @stevegardnersa, I have the same issue. 
@hypery2k Any plans for a new release soon? :)
